name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: '0 0 1 * *' # At 12:00 AM, on day 1 of the month

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: ░▒▓█
          TIME_RANGE: 'all_time'
          SHOW_MASKED_TIME: true
          SHOW_OS: true
          SHOW_PROJECTS: false
          SHOW_PROFILE_VIEWS: false
          SHOW_EDITORS: true
          SHOW_LANGUAGE_PER_REPO: true
          SHOW_LOC_CHART: true
          SHOW_LINES_OF_CODE: true
          SHOW_SHORT_INFO: true
